/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_ac_nottingham_hybridarcade_encoding_JabEncoder */

#ifndef _Included_uk_ac_nottingham_hybridarcade_encoding_JabEncoder
#define _Included_uk_ac_nottingham_hybridarcade_encoding_JabEncoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uk_ac_nottingham_hybridarcade_encoding_JabEncoder
 * Method:    saveEncoding
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_uk_ac_nottingham_hybridarcade_encoding_JabEncoder_saveEncoding
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     uk_ac_nottingham_hybridarcade_encoding_JabEncoder
 * Method:    readEncoding
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_uk_ac_nottingham_hybridarcade_encoding_JabEncoder_readEncoding
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
